---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beszel-agent
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: kubernetes
  source:
    repoURL: "https://github.com/fabricesemti80/project-homelab.git"
    path: kubernetes/apps/monitoring/beszel-agent
    targetRevision: main
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
