---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./http-route.yaml
commonAnnotations:
  external-dns.alpha.kubernetes.io/hostname: grafana.krapulax.dev
  external-dns.alpha.kubernetes.io/target: external.krapulax.dev
