---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-storage
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/fabricesemti80/project-homelab.git"
    path: kubernetes/storage/nginx-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
