---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: glance-configmap
    files:
      - glance.yml
resources:
  - ./http-route.yaml
