services:
  traefik:
    image: traefik:v2.11
    platform: ${HOMELAB_DOCKER_PLATFORM:-linux/amd64}
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      CF_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN:-}
      CF_ZONE_ID: ${TRAEFIK_CLOUDFLARE_ZONE_ID:-}
      CF_EMAIL: ${TRAEFIK_CLOUDFLARE_EMAIL:-}
    command:
      - --api
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --serversTransport.insecureSkipVerify=true
      - --log.level=${TRAEFIK_LOG_LEVEL:-DEBUG}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOMELAB_DOCKER_ROOT:-.}/runtime/traefik/dynamic:/etc/traefik/dynamic:ro
      - ${HOMELAB_DOCKER_ROOT:-.}/runtime/secrets/omni/server-chain.pem:/etc/traefik/omni/server-chain.pem:ro
      - ${HOMELAB_DOCKER_ROOT:-.}/runtime/secrets/omni/server-key.pem:/etc/traefik/omni/server-key.pem:ro
    networks:
      - proxy

networks:
  proxy:
    name: homelab_proxy
