---
metadata:
  namespace: default
  type: MachineClasses.omni.sidero.dev
  id: proxmox-worker
spec:
  matchlabels: []
  autoprovision:
    providerid: proxmox
    kernelargs: []
    metavalues: []
    providerdata: |
      cores: 2
      sockets: 1
      memory: 8192
      disk_size: 20
      network_bridge: vmbr0
      storage_selector: name == "ceph-proxmox-rbd"
      disk_ssd: true
      disk_discard: true
      disk_iothread: true
      disk_cache: none
      disk_aio: io_uring
      additional_disks:
        - disk_size: 50
          storage_selector: name == "ceph-proxmox-rbd"
          disk_ssd: true
          disk_iothread: true
          disk_discard: true
          disk_cache: none
          disk_aio: io_uring
