apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
type: Opaque
stringData:
  adminID: admin
  adminKey: ENC[AES256_GCM,data:LBeUeoXgFoMUfZmXwS7COi5OKFfDnjBGqsDGLJBxMkQ9LKF6kIvztA==,iv:O9YZnlQGlk2rgT2ysF7rSUXvy/ALpXUacG4WGH520Ec=,tag:jqIj7vwbYSSblDLs4ULt8g==,type:str]
  userID: csi-user
  userKey: ENC[AES256_GCM,data:KfT2xB2BJc2SZ0dOvFJOcBjwsKEg+frxbS8PMxV7XB9PdT+cxkayAg==,iv:dvLFtXcAAK3Hxlav0nBakrUBsS9hhob3HHdJWxCnvwg=,tag:pb1WvVmbzbr9zgPDtnJPIw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPejJ4d1BnbUVQK2dkR2pU
        Uk1STDI2Ty9JWWpZOFNyVWliYUxmaEpGQjI4CnlHM29aQVNlRHpNOVRuSW02SjEr
        WWZ5THg5UWY2cW9vckF0aGRqVG43WjgKLS0tIEdjM3ZhY2ZIbDRDUnM5cUx3a0Fi
        U3VqVCsrcXkwQ0paR2ZaNldWZ2taZlEKntmuhhj68Gn9f7QmbVBH23c1w4avcaAu
        oDRRrsET0SfgI2SgPZApAoAD+sOuLZ3knRc7MFkTr9kv18wFrAc6Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:hcApIEELZT06zPI0NHYDRWO6H4p4+/nq8VCAg27OxHLeMTeU4XMq+7NG3Bk9dHGG6uNTGbB+xFXXdKhebpD9Ij6KvsnE3+ZiQNWzjxFiQe2Q8a7yBbbCA1NQBblFueOSyuT0Q7Tl8VdoYPJz8EitUD9GdgEWqCN/EVRQf7AIZ+M=,iv:qp1QJifgnCxrSGD1dft/ljHOysWltgWkX7bmMkBpx9w=,tag:i7bnR4PGMEN//4Ult4KdVw==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
