csiConfig:
  - clusterID: a74bdf84-c6e5-4a3c-acf2-6c307f5c15a4
    monitors:
      - 10.0.70.10:6789
      - 10.0.70.11:6789
      - 10.0.70.12:6789
    adminID: admin
    adminKey: ENC[AES256_GCM,data:nS44ERD5CAHKZxfGVeoZoI6A9yt//akTB6odJ4oi4u746z178611wg==,iv:SPOgTDWVQIG+eTaCVPpwZv89btm7g9ezqOATfgWPguM=,tag:rf+WcDLgNu4F9DbS5JdHUw==,type:str]
cephFS:
  kernelMountOptions: ms_mode=prefercrc
provisioner:
  replicaCount: 3
nodeplugin:
  replicaCount: 3
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c0V0Uldob2I3KzVISGFU
        YkVmK01rSkoxT3NFYmFmMHFpaVBBWHhGa0J3CnVFakxyOEpuTVpSL3JlYXk5NHRq
        c0tOMGgwMndaSEl5dTBTcGpVRzYzOEEKLS0tIE00UFVwelczY09JNXhtYkZESWJP
        Q05hOVcrZ0FkblU3L0pNUUdzQUtnVVUKrOnELDUEyliisNyUaLjiE3vCwkObcH+E
        jpmGQ/34/Iq0BDAHHh3Y5h0ZphYO35n3ffQhuSNafk4zGv3nTWEuEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:JYboTjnS+9Y1NZ853cgZAWnTaS+3z3dw0LSuLXUN4JiVkkMJBfJPp+wNqTYAbLCw6T1CuWCa8c5c9Oq7OwLxzM6IZruQ3xpw9G4PY76B/UY+D1Ah5exBSCI/AeAVxfZnn4uNRE4I5BEiw6YmGp/WZ3j705nT28vSa3GcpItZOMo=,iv:t/lV5oG6ydIF3NCUuNjE18TkKfOXET8sHjES++/VsDw=,tag:lXTe+A9yhe421dMH+jNMFA==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.1
