---
controllers:
  qbittorrent:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: latest
        env:
          TZ: Europe/London
          PUID: "0"
          PGID: "0"
          UMASK: "002"
          WEBUI_PORT: "8080"
          TORRENTING_PORT: "6881"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 2Gi

defaultPodOptions:
  hostname: qbittorrent

service:
  app:
    controller: qbittorrent
    ports:
      http:
        port: 8080
        targetPort: 8080
      bittorrent:
        port: 6881
        targetPort: 6881
        protocol: TCP
      bittorrent-udp:
        port: 6881
        targetPort: 6881
        protocol: UDP

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 2Gi
    globalMounts:
      - path: /config
  downloads:
    enabled: true
    existingClaim: media-library-pvc
    globalMounts:
      - path: /downloads
        subPath: downloads/complete
  incomplete-downloads:
    enabled: true
    existingClaim: media-library-pvc
    globalMounts:
      - path: /incomplete-downloads
        subPath: downloads/incomplete
