apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:RW/J,iv:We9wzRpV7EyOCHeAFGE1syN502SCUu2ikaKdvNKzS7s=,tag:XVX0p3EUJp9KLgPr9BtKlQ==,type:str]
  url: ENC[AES256_GCM,data:fXSInqoHRcz3y7YZX0qAQg6RuLjN/Zrq5R0EABC4DbAJePT3bCtUczQZa7XT+wOrdka7hKQ=,iv:CqCvpH1Fk5IG4nnnJjP2sYryJMIWltA4LTo1Oet9amo=,tag:coo/QO0GQBMxpi+5vboUgA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcUp6V2NvZUpSYkpYZlFC
        SFh1dEQvQXFWeEkzdGpqZ1YwWkhmZVQ1blVBCk84Z3VCY0VFMzZXNUlORlF5ZEFr
        eDhHZiszMXpvVll6T2tOSmNpMXZZM1EKLS0tICtHS0RaSVcvMC8wMm1TMWV0Uzhp
        VWdkZjJlQnh5TmZCREVUMXFxWThFazgKSoIJB5VSMWreZ+JVJboTGv0C7evJsoGP
        7YHTEBQJhTRDSltQIr82uojvYQSvweQfl8pZjtdNnYQ87U4rs8TMUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T09:42:49Z"
  mac: ENC[AES256_GCM,data:+XqGRU9Y5zDzFSjDVTvBByXL/XKPC6fW4xouysa2MaK/mmCIhX5odjB/fYLv+T6Mz2E2IRzBUw9WwbZScf/+GXDIuRvrQS/IM0NTKeb5s50AaVa7P630rv/clLnPEAHY5fRhcewtNcGo/7nWc1i0w/SgnIo84vbnAsjXcDYKtMU=,iv:kbVaaAlL0TMpOJH3bDK30ehXN1kOl9ms4Fo5ZPWmJ4I=,tag:dT9eLGGLA16F7i+oZ+VoEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
