apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - krapulax.dev
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU3pGcFVkbVJHSnJ6ZUpM
        QmxkSHZrOXljeVppM1lYSWttUGtJaDFNZ3prCmFPMS9uVnhVaG1tU0d2TC90bm8v
        VTlKTVYvdjVUSEJnODBqMjQxdjN2aVkKLS0tIDg5YzJ1c2c1bk9jcGN2VXdYejQ5
        ODVVNVk0TEVjVUVEVzJPcHk3aDRuUmMKCNH5B6qZYHbK/vgQYiiHMqYNsZj3DjTf
        ntK/3RLkkUcrdu1Sitdk6K5LL4Rku1O327P5UkVFM8psI/xMDgHb8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:4mWDoNxCEs4vL8bQjjZzP+ZS4glgFTfEbFJQ4vmJQGcbR8YVQbled6csE8mKgZ416WrPyxHr2uoE/vRGsCGOND4BrdbxDT3tDnPBk+tf+DJ8QxqA2XwW2IxrukHX8LPYTRfUzGZ8y/HiZ6lHR8P2Llc2X0F8TNWzLV0c4xL0+Mo=,iv:qlFvefAilFSNfrFC8OVA99tvvhhkdow5B+paRikjdnA=,tag:DFv/Hx7aU71RwJtkONV6xA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
