apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:H0j7KzH3jxM7xSEl69itB6Gep0FWzLAMBjbN9yK6iINjTGkNEgbtWg==,iv:Ulx90kyDF++sD4qSynECNFZlVAiaHlutvGaya9p6QXY=,tag:h2y9nmnwQb5kLln8w1iTjA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRWx3dFgyR0E4dktDTlFH
        OTV3V3NyYXZFZXE3aDZ4SVI5UGYra3d4VnpNCjY3NTR0WGpIRU1rV1orYWFhMElJ
        bFN1dTlXRnlIOFVwbHM4TzE5S01tb1UKLS0tIFU4MkpoUDZKa0pMaU4vK0lBbVJz
        R0ZIYlBiQ0J3MkVFeXRPclgzTnNNT00K/2Sgoe8H4ih8CNMBe3HKPFb/LVJoYuve
        NdXB/Xfvm068fI6WBG0gaBIfv3z/Dh4zoc+3QkrGrEnNfKNu4uye9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:ncBDBKK9Lw3ye+zrbNLpw7+gbf8qaHtA8rahW3G0+JrtMlyRDNfs3tJgjMEuq/X2x1brb1eowpqGeITw5uveCb0roIvXN+LG+JEjpT87gHwahjaxP3FIyDJJBu9wlOPU8a7SifwVNdWDf1D4WowkBcg78lPHw0joMUieoyX3qEU=,iv:zQp4L5a1wH5NHhb032k6pTVB3vf75aTtFnTRqoZ34as=,tag:QNKZhh2GMRlc03/DSz++iA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
