---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-test-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 1Gi
