apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:8j6JDWSzFcfJJdR3iNmz6TQ7I5JfOvHU/5bLbBhATvF+K/Wu2VON7JgLnIsxUksXxOKXNZE=,iv:E5g1buELJ9nJpXMlfJh7wITAp/gR+VRIMhZurd/WTEY=,tag:IMRSryB2kWa6ttjGlmjEvw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmpSdlpjeHlPcGF0UXFX
        SW5hTHBNOTN4NzNsR1Q3ZVpqNk14VzBOU1U4ClBSNSthYkp2SXJnc3Naa0NRa2g2
        ZXBwUjBOUzBYS1ErOWhzcG1UcXI1Vm8KLS0tIFVoSmtscmkwcTdpNzdId2M4cGxx
        NzRtSXZXbEVFTlZwcVhpeXhoa2NueHcKsfHsIXHFdcUy50IC9Y9rH7UsLKRIWLtg
        OtW4LapatHundUlQCmQrexVS2O/sheKaY+j7H2aP16/GaNCIMYOy8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:fwRu3lpCbi8tS5iqb6v9yyUu8fe1cm15IhYQ5un8YD1iwCYYaPGU4A0adsGUIWRkNZTN4WxySoS8B7IRKphI6EFo4FpHR9w7B5bSex8yBMSEs2ChwQIUGgUZowclyzYBcXPRbcVm0+baQQOArQLcApum8hlOjlpwC+u/byqn4vI=,iv:2cG6AXaVPdt6ibF0WoKHpt6rDqwFBFboNpGkIn3J2QM=,tag:KvlhexJ6yjnwxe45j1QzUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
