apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:4hNrMrhdEgZBy1rFvBLTCnboEjV7KVWDTPnMltN4EzQQpn4A2qBq++F+ktapuK8FL/CZc99drOaoiWSv7A==,iv:ByqjYz6gHDSpLd1ImTKdrs/bXUXX8D67JAUqaoElCFY=,tag:eF6/5NdmBdHIbOe0XY5AQA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmpSdlpjeHlPcGF0UXFX
        SW5hTHBNOTN4NzNsR1Q3ZVpqNk14VzBOU1U4ClBSNSthYkp2SXJnc3Naa0NRa2g2
        ZXBwUjBOUzBYS1ErOWhzcG1UcXI1Vm8KLS0tIFVoSmtscmkwcTdpNzdId2M4cGxx
        NzRtSXZXbEVFTlZwcVhpeXhoa2NueHcKsfHsIXHFdcUy50IC9Y9rH7UsLKRIWLtg
        OtW4LapatHundUlQCmQrexVS2O/sheKaY+j7H2aP16/GaNCIMYOy8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T17:40:12Z"
  mac: ENC[AES256_GCM,data:eCyhFIWICqfMbQ20/ARvM4awEeaMXyz65CgbEzysASKJ9eSuwcYdS50oVTWUQlqwoq2DzhEAsJL5OOoUoaDzjLb/ylk9ZHT1hBSt91SUQN/6CxzHxoFhHvOBbltSaqqr0ttcBS+JCzTrtc3tkWQa57yCPcC5DbLH/TCALhy1FL8=,iv:msb08eFVw3pmt7vHWciINIJFvBGq1HkVvdiBss+XeIk=,tag:MRnuG0jBzw1chwvZQYyxWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
