fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: $2a$10$r0U.A7.56h6wtSWetPZVM.r/Ez4YlCbmjMTE5ZUdyoxJrNu44Zde.
    argocdServerAdminPasswordMtime: 2026-03-19T09:48:30
    githubSecret: aaebd543422ed4c2f5c8e89ad47fee36
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYTN1YmpJTlI4aCtlWlNl
        SWtNTlpwMm9SM2pDSVozR3AyQ1g4QW9YU1JNCkVpM1hmZURmME44QUxscVJWcE1y
        QTAzZWJFQUNjNTh5K0U5RmFWejhuUVkKLS0tIGVja0tPQTdJcnVwR2lCYTdvNXdH
        NHVNTHpQOGVxN2pNdy90TDZXTVVidEUKv0+yWCyRe+QBNXoPBkbPajmQdGtizcjw
        RIKr5gMOCPhUixLkU7fkTxpvJL6cZw1bRbU9yKHcWVyGroY4T8S6oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:cW95hiwljdLlvL+GNLpRLo+Nmy1uzw/oJ9ATX3JSXSGCHuw/p98SBWDyWV6RNQEjRMMMwBSzuNOej3kkbtukh8GH4l7XnybHVl+mlzUk7R6qxhzFyHRPiP7GmKDRaEXXYiMVi6vMQSwH+7jzx39+krjjGSyuohIdIXy6Pl2ANtM=,iv:N5LKjG5yC12Penw+tOv+5ZI7/D5ylnl89948sZt2lRk=,tag:xHlrUR6C547pjniueFWRxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
