apiVersion: v1
kind: Service
metadata:
  name: envoy-external
  namespace: network
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 10080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 10443
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: envoy-external
    gateway.envoyproxy.io/owning-gateway-namespace: network
  type: ClusterIP
