---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: immich-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: immich-secrets
    namespace: media
    type: Opaque
  secrets:
    - IMMICH_DB_PASSWORD
