apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:vBET8JJsOmDXT83acXLLFvfmzh+jO+649uZUqN/irvFHwndoEkcE0+g/gXXjNI1EgBCjheeXFu4RvQkxuhyVLuYnO4JQa64sXgY2,iv:zCcTl/7o9h+E/e2Larc8Mz5BI/AQPADjsICpoW+wbes=,tag:KMUTO97Eov0QEqdBVdXALg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV2I2RFkwNzdVVnlORTlI
        Zis4ZjJiNWd1ZzBMdTA5eVFRSTJGNEFUeFM4CkxXSlZJRkdEeEZLcmVQUk41OTRt
        eWhCZUU5NFZTNGJXS3VBK1RWZkkza0EKLS0tIEk0a3NveWJpWEQ5YVZKRFZ3dGNm
        SmdQOHZKbWEvSDhYVzA1eS8yd1FmNE0KKLAGvqzZ7RKatnEvqmXVhFbFyn3q38LP
        kTHtAlVddRwO/1bs3PlxRAdUsixauuM7r/bhylTceume1LsEvW/39Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:30Z"
  mac: ENC[AES256_GCM,data:Cj7vLoSEh9Jf+X5o5Ydp+Vd87bmJrM2ujrIT05cZ8WPf4ROV5AcjOuvD9XOZnCyQjumRLQQPatywziNA5D1pwp1eaFkn4+4i1Qw56oTWm9TlHVns6gDE1DUwJIRT0Z5p2K8xH2CPvbxukltZAR4KenmsKozMdjA3xPRCgGk/ZBQ=,iv:dsYo40LqnVY13u4Dvmr0IfW3cuZPPtyX4HVbzq1fcz4=,tag:3jgJ1KvuptHT2ZjHuyy4cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
