---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.40.101:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.40.101"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-ctrl-01"
    ipAddress: "10.0.40.90"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:79:b5:8f"
        dhcp: false
        addresses:
          - "10.0.40.90/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
        vip:
          ip: "10.0.40.101"
      - deviceSelector:
          hardwareAddr: "bc:24:11:ce:0c:fb"
        dhcp: false
        addresses:
          - "10.0.70.90/24"
        mtu: 1500
  - hostname: "k8s-ctrl-02"
    ipAddress: "10.0.40.91"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:95:de:4d"
        dhcp: false
        addresses:
          - "10.0.40.91/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
        vip:
          ip: "10.0.40.101"
      - deviceSelector:
          hardwareAddr: "bc:24:11:33:c5:5d"
        dhcp: false
        addresses:
          - "10.0.70.91/24"
        mtu: 1500
  - hostname: "k8s-ctrl-03"
    ipAddress: "10.0.40.92"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:72:f8:31"
        dhcp: false
        addresses:
          - "10.0.40.92/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
        vip:
          ip: "10.0.40.101"
      - deviceSelector:
          hardwareAddr: "bc:24:11:16:28:ab"
        dhcp: false
        addresses:
          - "10.0.70.92/24"
        mtu: 1500
  - hostname: "k8s-wrkr-01"
    ipAddress: "10.0.40.93"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:47:58:58"
        dhcp: false
        addresses:
          - "10.0.40.93/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:5f:9d:d6"
        dhcp: false
        addresses:
          - "10.0.70.93/24"
        mtu: 1500
  - hostname: "k8s-wrkr-02"
    ipAddress: "10.0.40.94"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b7:c1:78"
        dhcp: false
        addresses:
          - "10.0.40.94/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:ed:4f:eb"
        dhcp: false
        addresses:
          - "10.0.70.94/24"
        mtu: 1500
  - hostname: "k8s-wrkr-03"
    ipAddress: "10.0.40.95"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:4d:84:5c"
        dhcp: false
        addresses:
          - "10.0.40.95/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.40.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:14:a5:8d"
        dhcp: false
        addresses:
          - "10.0.70.95/24"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-registries.sops.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
