services:
  omni-proxmox:
    image: ghcr.io/siderolabs/omni-infra-provider-proxmox:latest
    container_name: omni-proxmox
    restart: unless-stopped
    extra_hosts:
      - "omni.krapulax.dev:172.19.0.8"
    environment:
      - PROXMOX_ENDPOINT=${PM_API_URL}
      - PROXMOX_TOKEN_ID=${PM_API_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PM_API_TOKEN_SECRET}
      - PROXMOX_INSECURE=true
    volumes:
      - ./config.yaml:/config.yaml
      - ${HOMELAB_DOCKER_ROOT:-.}/runtime/secrets/omni/full-chain.pem:/etc/ssl/certs/ca-certificates.crt:ro
    command:
      - "--config-file"
      - "/config.yaml"
      - "--omni-api-endpoint"
      - "https://omni.krapulax.dev:8443/"
      - "--omni-service-account-key"
      - "${OMNI_SERVICE_ACCOUNT_KEY}"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: homelab_proxy
