services:
  whoami:
    image: traefik/whoami:latest
    platform: ${HOMELAB_DOCKER_PLATFORM:-linux/amd64}
    container_name: whoami
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: Host(`${WHOAMI_HOSTNAME:-whoami.krapulax.dev}`)
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.services.whoami.loadbalancer.server.port: "80"
    networks:
      - proxy

networks:
  proxy:
    name: homelab_proxy
