---
version: '3'

tasks:

  init:
    desc: Bootstrap the management host from inside this repo
    cmd: bash {{.ROOT_DIR}}/scripts/management-init.sh
    preconditions:
      - test -f {{.ROOT_DIR}}/scripts/management-init.sh

  bootstrap:
    desc: Bootstrap the management VM over SSH from this workstation
    cmd: bash {{.ROOT_DIR}}/scripts/bootstrap-management-vm.sh
    preconditions:
      - test -f {{.ROOT_DIR}}/scripts/bootstrap-management-vm.sh
