---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-configmap
  namespace: media
data:
  recyclarr.yml: |
    sonarr:
      series-1080p:
        base_url: !env_var SONARR_URL
        api_key: !env_var SONARR_API_KEY
        delete_old_custom_formats: true
        quality_definition:
          type: series
          preferred_ratio: 0.5
          qualities:
            - name: Bluray-1080p
              min: 5
              max: 22
              preferred: 18
            - name: WEBDL-1080p
              min: 5
              max: 22
              preferred: 18
            - name: WEBRip-1080p
              min: 5
              max: 22
              preferred: 18
            - name: HDTV-1080p
              min: 5
              max: 22
              preferred: 18
        quality_profiles:
          - trash_id: 72dae194fc92bf828f32cde7744e51a1
            name: Series 1080p
            reset_unmatched_scores:
              enabled: true
            upgrade:
              allowed: true
              until_quality: WEB 1080p
              until_score: 10000
