apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:1vwwWnHhdPCuQvY8KYdDtIAXCiu2py74eJFajmW0JSw8AGfIzOVijieMnqM2Qt1O3WyIcskDytQFbA08xCSnrNEc+s01dLdTOpeq/fYfKoEsbBhUs2ORjg+FrGKxK0DsWyaP6nbpM5V2CUo0bsoHLZSwIoxbC8eyO80fyDOTz7PX464NjFXp2BENprfLj5N2NQzg+iC3pE+sRsFBe5o9R/mZPORD1KV0KgL55bACF2EMwsowdHYQz1yASww4u7Ng8t0RuvepnZNbHhToWg/XBHPNXipuI6lq3rDG+JKw6a5wwUmnmVYWubjM8ZG52NWR8uHWyh1p0A==,iv:8GuUj+svJeW18D8YNtohPCqpiTLoXSUubgkaFrexgOs=,tag:oX0mfaW3lEyL//mljRSNkQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjdtWCtoK056V3lBOW1s
        RXRCSFV0NnJPajNNNmlzdHdTdGVkOGs0SzA4CksyeXFjaXVqRHBzVmxMa1paZnVh
        ak55MzVxVE15cW82UkdPSkFRQ0t2dzgKLS0tIEUyNWgrdmE0TTNhRW1taG8zM3p4
        MUR2V0h6YitVKzhncElDbmNlaVYyMmsK0HMVibSC6q660K+LY3yubuWc2jCGvIr9
        ZP9AebLxI+b/TZwe8UiQRl6nLaJ00pn85owP6TA/AsCsISsb6RxNNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:K8JIcOrfpFXcIUKQ5RhL5jWhoS5+ivswhpoH2ADdygEJOdQmJgp+qDCkE57vaDk8r9vw/AHdSaDgVl4+HXyiDGOv2H2GMt4VfeqHuBFZ4IEvgFi1OOrMdnx+2qHrXmpHFcZnObmyrlX7H+8GkKvil8yZdv/Qimb21DCZhSyidh4=,iv:KPkvkk9d1xp5+s/epLwMR3n7nJawuD6A+zI3a4wx6T4=,tag:IUe0sVeSirkd3NcoI4Y7Vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
