apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.krapulax.dev
      recordType: CNAME
      targets:
        - c153a412-005f-4c07-8b89-34ec5628005a.cfargotunnel.com
    - dnsName: nginx-test.krapulax.dev
      recordType: CNAME
      targets:
        - c153a412-005f-4c07-8b89-34ec5628005a.cfargotunnel.com
    - dnsName: grafana.krapulax.dev
      recordType: CNAME
      targets:
        - external.krapulax.dev
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhczV2dVh3Y296aWdHM1NL
        MDdwOEtKRzhQcWpiTjFBWnIxOVN0STNGY2xBCk5yYVVxTFl4dXFDNWNueTgrV20r
        aG9tV1BpZXI4cXJFbmpoL3VjZitYU28KLS0tICtuWWdoUEt3c1ZSSEJzVnNCV1VL
        QlpGRVpML1BRdjZ5eHlpOVRIWmR2L2MK7iNw6rIgNsRcu4r1TO1zTQdN/xeIVLhv
        8qP54z1RN/hGjnxakVo7ROnAHA6cUpzZ0caJ28Q6fw3hd4qsGo707g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:ZoijXH17uOfu+sqX1xj7BWfVq0FMxr00//AWGyL7KoBWc84uRWNtaQ/Ve00DczwKG4Ro8AEeXpnU0fnA7byOmuKnUtTRxjfjDqwQ8hMAnPBurAs/fo5v1E6pbmaFLeSxraYKNQdETsDI3yp0Ctk8DJn9mTiAjq45uLGyQCC2xsQ=,iv:OjkIormoySbYT4+53XVz3cUOpx03dU8dLwkKP3ApHi0=,tag:59si/Rr4bRNZMJrXt2OC8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
