apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lQv5wSHNDBOT47aVKr1lgDF9VJOXSZJH+xqEQ3RjSMvt3MOMioWP7BbY/I3RndKCF/CEaoDAkhnOumCVNfPdIYvgTRsYZJMDekB2vXJ6a3H7nxNFKbM7qdynntZAPCPmSVVz/uau6NYONXhaapPzsrHqrecu79Px+XbcYH5FMxTeZLEGLF6OgQtMOMZZ7N0tse8azQm/KmOirsWFfG6QLwi5iBCqohu9de53M+w7etdK7S3YlVUC+w==,iv:VRMxYHDoxvwVY4ufksuUf2EQl+1QwRkDAFzg6EM3QiQ=,tag:iAWH9Y313/cohebtUjMRaw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENGZHeUJlQm4vRW0xMFds
        bENvbkhRc1lveVdUQTZkNFk1SS9mTWp5VDFRCkhJSGRmaGxDaS9JcHg5SG9SWml4
        eGd5UUZGTGIycE5NdnBKNjQ0NWV2NDQKLS0tIGZXZnZsUUZZdWlFaDY4L0pSdllY
        aHo1dk5XNCtKalN4bkluZWRuYVFwVkkKPusdT4LOvfevWLretWh/X5OeMWpnv1J+
        wvkfk94J4Y6w3C1oLZVJHp0KrRyHmFdEK+UzyJE8wQ3sFPKpcVOUeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:dDgGBdIHtbKqDBYSG8S3AN99H5j+KIdriGdN3T0EA23FZuLB3fc3s8XUfIF55nK9t4MFvsE520RurYJg7qAugghUYng0Jo++AnlfJQXRZrtsiejmtwt9gYS6Y0y2a+CMgt7zTJvIc9cuz/2lwaYjK58CYRfNK55U0olZCB9EpCY=,iv:rQVy87pc7TtLjSFW3MKnG1vfBg16HYIbu27qWfFclNs=,tag:chbOHlM4g6PnaBINu95z7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
