fullnameOverride: k8s-gateway
domain: krapulax.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 10.0.40.153
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bVlXQ0dNQzRoMDkyWGxr
        eDZmTU5ZRVVQbk5pZFRMSFprSTZwYzNMejEwClVxWmhqRlpsMittTHdzV29QSW1G
        RVUxRUhjZ1BwRHpKK3pvd2g1SWtjSWsKLS0tIGRFcXN1TEVReHd1V3NyTE1qSE13
        MGdFMTc1VjF0dVYzMHF3ZjBpZFFNOGcKVUaKFxR5tp8dZcFwM3ktOaZ6wFhrs192
        y1fxibN6AKERcx5eG8KnE29KNCPR6FoJCQLTB+mcWeCjZKQGoD7dsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:PIa4rJQy+SfmD8/Tu102WYpRRWE42t03T3qmsVw3u3Vey2MyRAvnMHwtzROWxSbri1nMrwtEV4fm0+jiDs1p1AGFExmY8xRwraHKgNw0UzghaXd+dWzWTPkEBHYvZ3hXWu0Lx3jV+ImGNf75rMfUyp9VEJKuToAaUrgUyesi5L8=,iv:iL5OXOX+0DCHUkOwBUhm5+TT2b8vGcqxO4Dp4fSX9EI=,tag:IspYtKbknB5iQr6A3EJNQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
