---
controllers:
  jellyfin:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/jellyfin
          tag: latest
        env:
          TZ: Europe/London
          PUID: "1000"
          PGID: "100"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8096
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 6Gi

service:
  app:
    controller: jellyfin
    ports:
      http:
        port: 8096
        targetPort: 8096

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 5Gi
    globalMounts:
      - path: /config
  cache:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 5Gi
    globalMounts:
      - path: /cache
  media:
    enabled: true
    existingClaim: media-library-pvc
    globalMounts:
      - path: /data
