---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: beszel-agent-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: beszel-agent-secrets
    namespace: monitoring
    type: Opaque
  secrets:
    - BESZEL_AGENT_KEY
