---
controllers:
  glance:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: docker.io/glanceapp/glance
          tag: v0.8.4
        env:
          TZ: Europe/London
          DOMAIN: krapulax.dev
          PORT: &port 8080
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *port
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 256Mi
service:
  app:
    controller: glance
    ports:
      http:
        port: 80
        targetPort: *port
persistence:
  config-file:
    type: configMap
    name: glance-configmap
    globalMounts:
      - path: /app/config/glance.yml
        subPath: glance.yml
        readOnly: true
  data:
    type: emptyDir
    globalMounts:
      - path: /app/data
