grafana:
  adminUser: admin
  adminPassword: my-grafana-pa55w0rd
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMGNjelRsUklOZ1VqVGxu
        TUZWTENvM0tGTlFHTlo4WlNzYWFXckdXYWc4ClExNTZwSFZ4ZEIvSnU0UmpEUXFh
        T0R5NUVoR21kaThid2oya3E4MDRTQU0KLS0tIHNiMW1RZXlXTmZ5bmh2MDYvZEty
        amI4TWliMWFrM1ZLdWYrdkhKZmtQVE0KUck/m1wK9pZPAmXO7EZ/n/4hrwzbrcln
        yjCneCgh7uhsdDOR0mUFe3F10eOoINMhodaOQFTyK4Rd9H//Y3DaqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:XDaNpMKtLyJWvGQI1LXQR9ho2tX6u1DDNcx8aZUK4JrrlJJlW5TD89LBzijJgHuGI3KqAFeD4KLKDeEsswNmv+pGLpHf3cnbsMSUZHUWVLgL5YvmmtzUY1FgW+97wuZWkU/hDRnZ9EFnzDTKaz1sJZEJ+ELflzDrxwRcDhdUcwM=,iv:dDy3KZ+7PqaRd7A8YDOZyNLPMGjFQnyw3QnVXMu2ofA=,tag:g9Wwp26+zXf255YdV3KccQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
