apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pyOo+ITN6xVP6YZbRdXAQHYgoyL1oNKqnAoJ6ll9oyHPSceXaeNLEQ==,iv:w0Z6ajj+OjvZhD+pCbtjyxBa3fEX65UQPWkY6q0hOt0=,tag:pCRKPc88de0tDJ9f7NtInw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUzVJZllBcWVPUDlJUWFJ
        OE9UdVVudHR0Yk5EZEZLcndQbE42SS83YTJVClJWd0tQSUlpa2pCTTEyNkRZaVZE
        cUc1UXBFSzV4c3NaVS9LbnZhNjc3TlUKLS0tIFVuRmovTHNqWWRidWtxcDVwU1RK
        QnIyZjlFVk52dG9ZZlhrajErWEdlYjQKKVRbcw5uNe0iBg+X5e3udnQQTiJOC4/H
        6yF5xPy7MIs7nS06fknfl8CjE8x6Fuxtj2TCSrCDL+4d2a7eVYhirw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:48:31Z"
  mac: ENC[AES256_GCM,data:7b7ThKXBmVjXGzsyCRWMnvi4A8R8n3gF3yKwgemqlszevLBgqyqz/gfPBS0yuXGY+RKTOmg07bWaUmVpjux9gjeayjMyXgKYjyKrxMVQuIGIp6rr4uB8RHPD7144PIn/MGW2iMhL5b4/t9qD2AMFcfOj9NeSL4b1wQ6q9OdnCVo=,iv:gfYnSJOnUzvqu/4jgNVSLMjVLp8y/sLDNRZoCiw/J9k=,tag:KVWbJtrUbmFIa3cTDovWVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
